name: Build wfm-professional and wfm-telecom images
description: 'Reusable workflow to build wfm-professional and wfm-telecom images that can be plugged into wfm, comms, and platform builds'

on:
    workflow_call:
      inputs:
        acr:
          description: 'IQGeos Azure container registry server name'
          required: true
          type: string
        harbor:
          description: 'IQGeos Harbor container registry server name'
          required: true
          type: string
        updated_tags:
          description: 'Comma-seperated list of new tags to retag the multi arch image'
          required: true
          type: string
        version:
          description: 'Version to build'
          required: true
          type: string
      secrets:
          REGISTRY_LOGIN_SERVER:
              required: true
          REGISTRY_USERNAME:
              required: true
          REGISTRY_PASSWORD:
              required: true
          HARBOR_CLI_SECRET:
              required: true
          HARBOR_USERNAME:
            required: true

jobs:
    editions-version:
        runs-on: ubuntu-latest
        steps:
            - name: Determine editions version
              run: |
                    "run skopeo to determine latest value of editions image(s)?"
                    "increment the major, minor, or patch version by 1? How will editions versioning be handled?"
                    "set new version of editions based on what the latest version is and increment it to pass downstream to image builds"
    build-editions-wfm-professional-build:
        uses: IQGeo/devops-engineering-ci-public-build-multi-arch-workflow/.github/workflows/build-multi-arch.yml@main
        with:
            version: ${{ inputs.version }}
            module: editions-wfm-professional-build
            dockerfile_path: editions-wfm-professional/dockerfile.build
            docker_context: .
            acr: ${{ inputs.acr }}
            harbor: ${{ inputs.harbor }}
            updated_tags: ${{ inputs.updated_tags }}
        secrets: inherit
    build-editions-wfm-professional-appserver-tools:
        needs: build-editions-wfm-professional-build
        strategy:
            matrix:
                module: [ editions-wfm-professional-appserver, editions-wfm-professional-tools]
                dockerfile_path: [ editions-wfm-professional/dockerfile.appserver, editions-wfm-professional/dockerfile.tools]
                exclude:
                    - module: editions-wfm-professional-appserver
                      dockerfile_path: editions-wfm-professional/dockerfile.tools
                    - module: editions-wfm-professional-tools
                      dockerfile_path: editions-wfm-professional/dockerfile.appserver
        uses: IQGeo/devops-engineering-ci-public-build-multi-arch-workflow/.github/workflows/build-multi-arch.yml@main
        with:
            version: ${{ inputs.version }}
            module: ${{ matrix.module }}
            dockerfile_path: ${{ matrix.dockerfile_path }}
            docker_context: ./editions-wfm-professional
            acr: ${{ inputs.acr }}
            harbor: ${{ inputs.harbor }}
            updated_tags: ${{ inputs.updated_tags }}
        secrets: inherit
    build-editions-wfm-telecom-build:
        uses: IQGeo/devops-engineering-ci-public-build-multi-arch-workflow/.github/workflows/build-multi-arch.yml@main
        with:
            version: ${{ inputs.version }}
            module: editions-wfm-telecom-build
            dockerfile_path: editions-wfm-telecom/dockerfile.build
            docker_context: .
            acr: ${{ inputs.acr }}
            harbor: ${{ inputs.harbor }}
            updated_tags: ${{ inputs.updated_tags }}
        secrets: inherit
    build-editions-wfm-telecom-appserver-tools:
        needs: build-editions-wfm-telecom-build
        strategy:
            matrix:
                module: [ editions-wfm-telecom-appserver, editions-wfm-telecom-tools]
                dockerfile_path: [ editions-wfm-telecom/dockerfile.appserver, editions-wfm-telecom/dockerfile.tools]
                exclude:
                    - module: editions-wfm-telecom-appserver
                      dockerfile_path: editions-wfm-telecom/dockerfile.tools
                    - module: editions-wfm-telecom-tools
                      dockerfile_path: editions-wfm-telecom/dockerfile.appserver
        uses: IQGeo/devops-engineering-ci-public-build-multi-arch-workflow/.github/workflows/build-multi-arch.yml@main
        with:
            version: ${{ inputs.version }}
            module: ${{ matrix.module }}
            dockerfile_path: ${{ matrix.dockerfile_path }}
            docker_context: ./editions-wfm-telecom
            acr: ${{ inputs.acr }}
            harbor: ${{ inputs.harbor }}
            updated_tags: ${{ inputs.updated_tags }}
        secrets: inherit